### ISSUE TITLE
Error: Only variables should be passed by reference (Subs-UltimateMenu.php)

### ISSUE THREAD

**Issue by tulliana** [live627/smf-ultimate-menu#2]
8: Only variables should be passed by reference
File: /home/*******/public_html/forum/Sources/Subs-UltimateMenu.php
line: 19 

I see thousands of this error in the forum. What is the solution?

**line: 19**
`	

$hooks = explode(',', $modSettings['integrate_menu_buttons']);`

**Comment by live627** [comment]
I might have already fixed this in v1.0.2. You can grab it at https://github.com/live627/smf-ultimate-menu/releases/download/v1.0.2/smf-ultimate-menu.tar.gz

Are you on version 1.0?

**Comment by tulliana** [comment]
This solution solved my problem, thank you
